version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: palmera-rentals
    restart: always
    environment:
      POSTGRES_USER: palmera-rentals
      POSTGRES_PASSWORD: jkjd#kk%ql24sd$
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
